version: "3.6"

services:
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: client-container1
    command: "npm start"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/var/www/client"
    networks:
      - yolo_net
    image: manasseh2004/client:v1.1.0

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container1
    command: "npm start"
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/var/www/backend"
    networks:
      - yolo_net
    image: manasseh2004/backend:v1.1.0

  yolo.db:
    image: mongo:latest
    container_name: yolo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password 
      MONGO_INITDB_DATABASE: local 
    ports:
      - "27018:27017"

    networks:
      - yolo_net

networks:
  yolo_net:
    driver: bridge
